version: '3'
services:
  app:
    container_name: top_g
    build: .
    volumes:
      - /opt/discbot/.env:/app/.env
    env_file:
      - /opt/discbot/.env
    #FIXME 
  redis:
    container_name: redis
    ports: 
      - 6379:6379
    image: redis
