version: '3'
services:
  app:
    container_name: discord_bot
    build: .
    volumes:
      - ./.env:/app/.env
      - ./assets:/assets
    env_file:
      - ./.env
    depends_on:
      - redis
  redis:
    container_name: redis
    ports: 
      - 6379:6379
    image: redis
    volumes:
      - ./redis-volume:/data
